{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sbl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sbl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sbl/sbl_{{ version }}.tar.gz
  sha256: 7c5accfbe2e2e71c45c80610e8aafaa17ec436ce8cc9faac2ee54e1023d3bff3

build:
  merge_build_host: True  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('sbl')"           # [not win]
    - "\"%R%\" -e \"library('sbl')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sbl
  license: GPL-3.0-only
  summary: Implements sparse Bayesian learning method for QTL mapping and genome-wide association
    studies.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sbl
# Type: Package
# Title: Sparse Bayesian Learning for QTL Mapping and Genome-Wide Association Studies
# Version: 0.1.0
# Author: Meiyue Wang and Shizhong Xu
# Maintainer: Meiyue Wang <mwang024@ucr.edu>
# Description: Implements sparse Bayesian learning method for QTL mapping and genome-wide association studies.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Depends: stats, R (>= 2.10)
# RoxygenNote: 6.1.0
# Date: 2018-10-17
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-10-17 19:29:53 UTC; Dell
# Repository: CRAN
# Date/Publication: 2018-10-26 15:50:03 UTC
